services:
  node1:
    build: .
    container_name: node1
    environment:
      - RAFT_NODE_ID=node1
      - RAFT_ADDRESS=node1
      - RAFT_PORT=5000
    networks:
      raft_net:
        aliases:
          - node1
    ports:
      - "5000:5000"
    # If you have a healthcheck or other configurations, add them here

  node2:
    build: .
    container_name: node2
    environment:
      - RAFT_NODE_ID=node2
      - RAFT_ADDRESS=node2
      - RAFT_PORT=5000
    networks:
      raft_net:
        aliases:
          - node2
    ports:
      - "5001:5000"

  node3:
    build: .
    container_name: node3
    environment:
      - RAFT_NODE_ID=node3
      - RAFT_ADDRESS=node3
      - RAFT_PORT=5000
    networks:
      raft_net:
        aliases:
          - node3
    ports:
      - "5002:5000"

networks:
  raft_net:
