version: "3.8"

services:
  node0:
    build: .
    container_name: raft_node_0
    environment:
      - NODE_ID=0
      - NODE_PORT=5000
      - NUM_PEERS=2
      - PEER_0_HOST=raft_node_1
      - PEER_0_PORT=5001
      - PEER_1_HOST=raft_node_2
      - PEER_1_PORT=5002
    ports:
      - "5000:5000"

  node1:
    build: .
    container_name: raft_node_1
    environment:
      - NODE_ID=1
      - NODE_PORT=5001
      - NUM_PEERS=2
      - PEER_0_HOST=raft_node_0
      - PEER_0_PORT=5000
      - PEER_1_HOST=raft_node_2
      - PEER_1_PORT=5002
    ports:
      - "5001:5001"

  node2:
    build: .
    container_name: raft_node_2
    environment:
      - NODE_ID=2
      - NODE_PORT=5002
      - NUM_PEERS=2
      - PEER_0_HOST=raft_node_0
      - PEER_0_PORT=5000
      - PEER_1_HOST=raft_node_1
      - PEER_1_PORT=5001
    ports:
      - "5002:5002"
